name: Pothole Manager build Driver Build
# https://developer.android.com/build/building-cmdline
on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - feature/**

jobs:
  kdoctor:
    name: Install and run kdoctor
    runs-on: macos-latest
    steps:
      - name: Checkout the code to a specific branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu' #corretto,temurin or oracle
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install kdoctor
        run: brew install kdoctor

      - name: Run kdoctor
        run: kdoctor
