name: Pothole Manager build Driver Build
# https://developer.android.com/build/building-cmdline
on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - feature/**

jobs:
  code_quality:
    name: Code quality
    runs-on: macos-latest
    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Run check
        run: echo 'Done!'

  build_android:
    needs: code_quality
    name: Build, test, check -> (:androidApp)
    runs-on: macos-latest
    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu' #corretto,temurin or oracle
          java-version: '17'

      - name: Cache & Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        shell: bash
        run: chmod +x ./gradlew

      - name: Build, test, check (:app)
        shell: bash
        run: ./gradlew :app:assembleDevDebug


  build_ios:
    needs: code_quality
    name: Build, test, check -> (:iosApp)
    runs-on: macos-latest
    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu' #corretto,temurin or oracle
          java-version: '17'

